# Generated by Django 4.0.4 on 2023-02-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
