# Generated by Django 4.0.4 on 2023-02-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
