# Generated by Django 4.0.4 on 2023-03-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='photo',
            new_name='product',
        ),
    ]
